// Initial authentic dataset for KTSZE Világ- és Utcazenei Fesztivál 2026 (Pünkösd)
import { FESTIVAL } from './config';

export const DEFAULT_USERS = [
  { id: 'usr-1', name: 'Szilveszter', role: 'Nagyszínpad Koordinátor & Műszaki Vezető', badge: 'Technika', phone: '+36 30 987 6543', email: 'szilveszter@ktsze.hu', pin: '1532', radio: 'URH Ch-1' },
  { id: 'usr-2', name: 'Gábor', role: 'KTSZE Elnök & Főszervező', badge: 'Elnökség', phone: '+36 30 876 5432', email: 'gabor@ktsze.hu', pin: '1532', radio: 'URH Ch-1' },
  { id: 'usr-3', name: 'Zoltán', role: 'Pénzügyi & Pályázati Felelős', badge: 'Pénzügy', phone: '+36 30 765 4321', email: 'zoltan@ktsze.hu', pin: '1532', radio: 'URH Ch-3' },
  { id: 'usr-4', name: 'Műszaki Stáb', role: 'Hang- és Fénytechnikus Csapat', badge: 'Technika', phone: '+36 30 654 3210', email: 'technika@ktsze.hu', pin: '1532', radio: 'URH Ch-2' },
  { id: 'usr-5', name: 'Önkéntes Csapat', role: 'Helyszíni Koordináció & Zsákos Ügyelet', badge: 'Helyszín', phone: '+36 30 543 2109', email: 'onkentes@ktsze.hu', pin: '1532', radio: 'URH Ch-4' },
];

export const STAGES = [
  { id: 'main_stage', name: 'Nagyszínpad (Fő tér)', location: 'Fő tér (Borok helyszíne)', type: 'Nagyszínpad', capacity: '4000 fő' },
  { id: 'small_stage_1', name: 'Kisszínpad 1 (Jurisics tér)', location: 'Jurisics tér (Ételek utcája)', type: 'Utcazene & Akusztik', capacity: '1200 fő' },
  { id: 'small_stage_2', name: 'Kisszínpad 2 (Várjátszótér)', location: 'Várjátszótér & Várárok', type: 'Gyerekbirodalom', capacity: '800 fő' },
  { id: 'street_points', name: 'Belvárosi Kapualjak', location: 'Kapualjak & Sétányok', type: 'Egyedi Zenészek', capacity: '200 fő' },
];

export const DAYS = FESTIVAL.days.map(d => d.name);

export const INITIAL_SCHEDULE = [
  // PÉNTEK NAGYSZÍNPAD
  {
    id: 'sch-1',
    stageId: 'main_stage',
    day: 'Péntek',
    time: '14:00 - 15:30',
    title: 'DJ Chill Afro Grooves',
    artist: 'DJ Desert Sound & Percussion',
    genre: 'Afrobeat / Desert Blues / Downtempo',
    soundcheck: '13:00 - 13:45',
    loadIn: '12:30',
    status: 'Visszaigazolva',
    stageManager: 'Szilveszter',
    notes: 'Chilles bevezető a borozáshoz a Fő téren'
  },
  {
    id: 'sch-2',
    stageId: 'main_stage',
    day: 'Péntek',
    time: '16:00 - 17:15',
    title: 'Kőszegi Vonósok & Világzenei Fúzió',
    artist: 'Kőszegi Vonós Kamaraegyüttes & Vendégek',
    genre: 'Ethno-Klasszikus fúzió',
    soundcheck: '14:30 - 15:30',
    loadIn: '13:30',
    status: 'Visszaigazolva',
    stageManager: 'Szilveszter',
    notes: '12 szék, kották, 8 mikrofon állvány'
  },
  {
    id: 'sch-3',
    stageId: 'main_stage',
    day: 'Péntek',
    time: '18:00 - 19:30',
    title: 'Besh o droM Koncert',
    artist: 'Besh o droM Produkció',
    genre: 'Balkan / Gypsy Brass / Punk',
    soundcheck: '17:15 - 17:45',
    loadIn: '16:00',
    status: 'Visszaigazolva',
    stageManager: 'Szilveszter',
    notes: 'Full tech rider beérkezve, 16 sáv keverő'
  },
  {
    id: 'sch-4',
    stageId: 'main_stage',
    day: 'Péntek',
    time: '20:30 - 22:00',
    title: 'VÁRDISCO: TornyosiGabi Warm-up',
    artist: 'TornyosiGabi DJ szett',
    genre: 'Classic Várdisco 90s & 2000s Hits',
    soundcheck: '20:00 - 20:20',
    loadIn: '19:30',
    status: 'Visszaigazolva',
    stageManager: 'Szilveszter',
    notes: 'Átalakul a színpad Várdiscovál! Füstgép, robotlámpák'
  },
  {
    id: 'sch-5',
    stageId: 'main_stage',
    day: 'Péntek',
    time: '22:00 - 23:30',
    title: 'VÁRDISCO: Kunyik & Magnus Retro Show',
    artist: 'DJ Kunyik & DJ Magnus B2B',
    genre: 'Várdisco Resident Classics & Club Hits',
    soundcheck: 'Line-check közben',
    loadIn: '21:00',
    status: 'Visszaigazolva',
    stageManager: 'Szilveszter',
    notes: 'Közönségcsúcs várható, kordonokat ellenőrizni!'
  },
  {
    id: 'sch-6',
    stageId: 'main_stage',
    day: 'Péntek',
    time: '23:30 - 02:00',
    title: 'VÁRDISCO FINÁLÉ: TISZTAFAXXA LIVE',
    featured: true,
    artist: 'TISZTAFAXXA (Szilveszter & Tesója)',
    genre: 'Heavy Festival EDM, Bass & All-out Party',
    soundcheck: '23:15 line-check',
    loadIn: '22:30',
    status: 'Visszaigazolva',
    stageManager: 'Szilveszter',
    notes: '02:00-kor csendrendelet miatt zene stop!'
  },

  // SZOMBAT NAGYSZÍNPAD
  {
    id: 'sch-7',
    stageId: 'main_stage',
    day: 'Szombat',
    time: '14:30 - 16:00',
    title: 'Flamenco Nuevo Trio & DJ Session',
    artist: 'Flamenco Nuevo Trio (Bécs/Bp)',
    genre: 'Flamenco & Akusztikus Világzene',
    soundcheck: '13:30 - 14:15',
    loadIn: '13:00',
    status: 'Visszaigazolva',
    stageManager: 'Szilveszter',
    notes: 'Kajon, 2 spanyolgitár mikrofonozás'
  },
  {
    id: 'sch-8',
    stageId: 'main_stage',
    day: 'Szombat',
    time: '16:45 - 18:15',
    title: 'Söndörgő Együttes',
    artist: 'Söndörgő',
    genre: 'Délszláv Tambura Világzene',
    soundcheck: '16:00 - 16:35',
    loadIn: '15:00',
    status: 'Visszaigazolva',
    stageManager: 'Szilveszter',
    notes: 'Kiemelt akusztikus tisztaság szükséges'
  },
  {
    id: 'sch-9',
    stageId: 'main_stage',
    day: 'Szombat',
    time: '18:45 - 20:15',
    title: 'Cimbaliband & Danics Dóra',
    artist: 'Cimbaliband',
    genre: 'Balkan Ethno-Jazz / Pop Világzene',
    soundcheck: '18:15 - 18:40',
    loadIn: '17:00',
    status: 'Visszaigazolva',
    stageManager: 'Szilveszter',
    notes: 'Koncertcimbalom színpadi helyének biztosítása'
  },
  {
    id: 'sch-10',
    stageId: 'main_stage',
    day: 'Szombat',
    time: '21:00 - 23:00',
    title: 'OCHO MACHO ÉLŐ NAGYKONCERT',
    featured: true,
    artist: 'Ocho Macho Zenekar (Kőszeg)',
    genre: 'Reggae / Ska / Punk / Latin World',
    soundcheck: '19:30 - 20:15 (zárt)',
    loadIn: '17:30',
    status: 'Visszaigazolva',
    stageManager: 'Szilveszter',
    notes: 'A fesztivál szombati fénypontja! VIP backstage felügyelet'
  },
  {
    id: 'sch-11',
    stageId: 'main_stage',
    day: 'Szombat',
    time: '23:15 - 01:30',
    title: 'Ocho Macho Aftershow DJ Party',
    artist: 'DJ Reggae & World Brass Special',
    genre: 'Ska-reggae-balkan after party',
    soundcheck: 'Line check',
    loadIn: '22:30',
    status: 'Tervezett',
    stageManager: 'Szilveszter',
    notes: '01:30-kor hangerő csökkentés'
  },

  // VASÁRNAP NAGYSZÍNPAD
  {
    id: 'sch-12',
    stageId: 'main_stage',
    day: 'Vasárnap',
    time: '15:00 - 16:30',
    title: 'Kelta Vándor & Romengo & Lakatos Mónika',
    artist: 'Romengo feat. Lakatos Mónika',
    genre: 'Oláhcigány Tradicionális Világzene',
    soundcheck: '14:00 - 14:45',
    loadIn: '13:30',
    status: 'Visszaigazolva',
    stageManager: 'Szilveszter',
    notes: 'Kannák, teknő, kanál és gitár mikrofonozás'
  },
  {
    id: 'sch-13',
    stageId: 'main_stage',
    day: 'Vasárnap',
    time: '17:15 - 19:15',
    title: 'Bohemian Betyars Nagykoncert',
    artist: 'Bohemian Betyars',
    genre: 'Speed-folk Freak-punk',
    soundcheck: '16:30 - 17:05',
    loadIn: '15:30',
    status: 'Visszaigazolva',
    stageManager: 'Szilveszter',
    notes: 'Kordonokat megerősíteni, hegedű adó-vevő'
  },
  {
    id: 'sch-14',
    stageId: 'main_stage',
    day: 'Vasárnap',
    time: '20:30 - 22:15',
    title: 'ESTI SZTÁRFELLÉPŐ: G.w.M / MAJKA LIVE',
    featured: true,
    artist: 'Sztárfellépő Produkció (Egyeztetés alatt)',
    genre: 'Urban Pop / Hip-hop Fesztivál Show',
    soundcheck: '19:30 - 20:00',
    loadIn: '18:00',
    status: 'Egyeztetés alatt',
    stageManager: 'Szilveszter',
    notes: 'Extra biztonsági stáb a nagyszínpad elé és backstage-hez'
  },
  {
    id: 'sch-15',
    stageId: 'main_stage',
    day: 'Vasárnap',
    time: '22:30 - 01:00',
    title: 'OPEN STAGE — Össznépi Jam Session',
    artist: 'Bárki felmehet zenélni! (Utcazenészek + Helyi tehetségek)',
    genre: 'Szabad Világzenei Örömzene',
    soundcheck: 'Gyors beülés',
    loadIn: 'Folyamatos',
    status: 'Jóváhagyva',
    stageManager: 'Szilveszter',
    notes: 'Nyitott mikrofonok, felügyelt keverőpult'
  },

  // HÉTFŐ NAGYSZÍNPAD
  {
    id: 'sch-16',
    stageId: 'main_stage',
    day: 'Hétfő',
    time: '14:30 - 16:30',
    title: 'Utcazenész Verseny Döntő & Gála',
    artist: 'Legjobb 5 Belvárosi Utcazenész Csapat',
    genre: 'Akusztikus / Népzene / Világzene',
    soundcheck: '13:30 - 14:15',
    loadIn: '13:00',
    status: 'Visszaigazolva',
    stageManager: 'Szilveszter',
    notes: 'Közönségszavazatok kihirdetése'
  },
  {
    id: 'sch-17',
    stageId: 'main_stage',
    day: 'Hétfő',
    time: '17:00 - 19:30',
    title: 'Parno Graszt & Fesztivál Zárókoncert',
    featured: true,
    artist: 'Parno Graszt',
    genre: 'Autentikus Cigány Világzene',
    soundcheck: '16:30 - 16:55',
    loadIn: '15:00',
    status: 'Visszaigazolva',
    stageManager: 'Szilveszter',
    notes: 'Fesztiválzáró KTSZE elnöki köszöntő a koncert előtt'
  },

  // JURISICS TÉR (KISSZÍNPAD 1 - ÉTELEK UTCÁJA)
  {
    id: 'sch-18',
    stageId: 'small_stage_1',
    day: 'Péntek',
    time: '15:00 - 18:00',
    title: 'Duo Corda Akusztikus Gitár & Hegedű',
    artist: 'Duo Corda',
    genre: 'Világzenei akusztik',
    soundcheck: '14:30',
    loadIn: '14:00',
    status: 'Visszaigazolva',
    stageManager: 'Önkéntes Csapat',
    notes: 'Gasztro zenei aláfestés'
  },
  {
    id: 'sch-19',
    stageId: 'small_stage_1',
    day: 'Szombat',
    time: '15:00 - 21:00',
    title: 'Balkan Brass Kvartett & Vendégzenészek',
    artist: 'Balkan Brass Band',
    genre: 'Rézfúvós balkán zene',
    soundcheck: '14:30',
    loadIn: '14:00',
    status: 'Visszaigazolva',
    stageManager: 'Önkéntes Csapat',
    notes: 'Váltásban a food truckok mellett'
  },

  // VÁRJÁTSZÓTÉR (KISSZÍNPAD 2 - GYEREKBIRODALOM)
  {
    id: 'sch-20',
    stageId: 'small_stage_2',
    day: 'Szombat',
    time: '10:30 - 12:30',
    title: 'Interaktív Ritmusműhely & Dobolás',
    artist: 'Kőszegi Zeneiskola Népzenei Műhely',
    genre: 'Gyerek népzene és ritmusjáték',
    soundcheck: '10:00',
    loadIn: '09:30',
    status: 'Visszaigazolva',
    stageManager: 'Gábor',
    notes: 'Gyerekeknek kézihangszerek'
  },
  {
    id: 'sch-21',
    stageId: 'small_stage_2',
    day: 'Vasárnap',
    time: '15:00 - 17:00',
    title: 'Kerekerdő Gyermekkoncert és Bábjáték',
    artist: 'Kerekerdő Együttes',
    genre: 'Gyermek világzene',
    soundcheck: '14:30',
    loadIn: '14:00',
    status: 'Visszaigazolva',
    stageManager: 'Gábor',
    notes: 'Családi délután'
  }
];

export const INITIAL_ARTISTS = [
  {
    id: 'art-1',
    name: 'TISZTAFAXXA',
    contact: 'Szilveszter',
    phone: '+36 30 123 4567',
    email: 'tisztafaxxa@koszeg.hu',
    fee: 0,
    feeType: 'Saját fellépés (KTSZE stáb)',
    contractStatus: 'Aláírva',
    paymentStatus: 'KTSZE Belső',
    techRider: 'Jóváhagyva (2x Pioneer CDJ 3000 + DJM A9 keverő, füstgép, monitor láda)',
    hospitality: '2 karton hideg ásványvíz, energiaitalok, törölköző',
    diet: 'Nincs speciális igény',
    accommodation: 'Helyi (Nem kér)',
    passes: 4
  },
  {
    id: 'art-2',
    name: 'Ocho Macho',
    contact: 'Kirchknopf Gergő / Menedzser',
    phone: '+36 30 987 6543',
    email: 'booking@ochomacho.hu',
    fee: 2200000,
    feeType: 'Átutalás / Kft számla',
    contractStatus: 'Aláírva',
    paymentStatus: 'Előleg kifizetve (50%)',
    techRider: 'Jóváhagyva (Line Array, fúvós szekció 4 wireless mic, in-ear utak)',
    hospitality: '10 fő melegvacsora koncert előtt, 3 karton mentes víz, kőszegi borok',
    diet: '2 fő vegetáriánus, 1 fő laktózérzékeny',
    accommodation: '5 kétágyas szoba Kőszegen (Hotel Írottkő)',
    passes: 4
  },
  {
    id: 'art-3',
    name: 'Besh o droM',
    contact: 'Kovács Zoltán (Tour Manager)',
    phone: '+36 20 222 3344',
    email: 'management@beshodrom.hu',
    fee: 1450000,
    feeType: 'Átutalás / Kft számla',
    contractStatus: 'Aláírva',
    paymentStatus: 'Fizetésre vár',
    techRider: 'Jóváhagyva (18 bemenet, harmonika mic, hegedű DI, rézfúvósok)',
    hospitality: '8 fő vacsora, szobahőmérsékletű víz, tea mézzel',
    diet: '2 vegetáriánus',
    accommodation: '4 szoba (Jurisics Panzió)',
    passes: 3
  },
  {
    id: 'art-4',
    name: 'Bohemian Betyars',
    contact: 'Fehér Gábor',
    phone: '+36 30 333 4455',
    email: 'koncert@bohemianbetyars.hu',
    fee: 1850000,
    feeType: 'Átutalás / Kft számla',
    contractStatus: 'Aláírva',
    paymentStatus: 'Fizetésre vár',
    techRider: 'Jóváhagyva (Gyors átszerelés, hegedű wireless, fúvós monitorok)',
    hospitality: '7 fő melegétel, kávé, gyümölcstál, hideg ásványvíz',
    diet: '1 vegán, 1 gluténmentes',
    accommodation: '4 kétágyas szoba',
    passes: 3
  },
  {
    id: 'art-5',
    name: 'Parno Graszt',
    contact: 'Oláh József',
    phone: '+36 30 777 8899',
    email: 'parnograszt@gmail.com',
    fee: 1950000,
    feeType: 'Átutalás / Kft számla',
    contractStatus: 'Egyeztetés alatt',
    paymentStatus: 'Fizetésre vár',
    techRider: 'Megérkezett (Kannák mikrofonozása, harmonika, hegedűk, gitárok)',
    hospitality: '10 fő melegétel, kávé, ásványvizek, gyümölcstál',
    diet: 'Hagyományos húsos ételek',
    accommodation: '5 szoba Kőszegen',
    passes: 4
  },
  {
    id: 'art-6',
    name: 'Várdisco Legends (Kunyik, Magnus, TornyosiGabi)',
    contact: 'Kunyik & Tornyosi Gábor',
    phone: '+36 30 444 8877',
    email: 'vardisco.legends@gmail.com',
    fee: 350000,
    feeType: 'Készpénz / Számla KTSZE',
    contractStatus: 'Aláírva',
    paymentStatus: 'Helyszínen fizetendő',
    techRider: 'Jóváhagyva (DJ pult magasítás, extra kontroll láda, füstgép)',
    hospitality: 'Ásványvizek, sörök, rágcsálnivaló a backstage-be',
    diet: 'Nincs speciális igény',
    accommodation: 'Helyi (Nem kér)',
    passes: 4
  },
  {
    id: 'art-7',
    name: 'Sztárfellépő (G.w.M / Majka egyeztetés)',
    contact: 'Menedzsment iroda Bp.',
    phone: '+36 70 555 1234',
    email: 'booking.sztar@gmail.com',
    fee: 3200000,
    feeType: 'Átutalás / Kft számla',
    contractStatus: 'Tárgyalás alatt',
    paymentStatus: 'Pályázati keretből',
    techRider: 'Bekérve (In-ear fülmonitorok, vezeték nélküli mikrofonpark)',
    hospitality: 'Zárható öltözősátor tükörrel, hidegtál, Red Bull, víz',
    diet: 'Egyeztetés alatt',
    accommodation: '4 superior szoba',
    passes: 6
  }
];

export const INITIAL_VENDORS = [
  // FŐ TÉR - BOROK HELYSZÍNE
  {
    id: 'ven-1',
    code: 'BOR-01',
    name: 'Stefanich Pincészet Kőszeg',
    category: 'Borászat (Fő tér)',
    location: 'Fő tér 1. pavilon',
    contact: 'Stefanich Zoltán',
    phone: '+36 30 222 1100',
    power: '1x16A (Hűtőkhöz)',
    water: false,
    trashBins: 1,
    trashBagsIssued: 6,
    deposit: 50000,
    fee: 120000,
    status: 'Települt / Ellenőrizve'
  },
  {
    id: 'ven-2',
    code: 'BOR-02',
    name: 'Tóth Pincészet Kőszeg',
    category: 'Borászat (Fő tér)',
    location: 'Fő tér 2. pavilon',
    contact: 'Tóth Ferenc',
    phone: '+36 30 333 2211',
    power: '1x16A (Hűtőkhöz)',
    water: false,
    trashBins: 1,
    trashBagsIssued: 6,
    deposit: 50000,
    fee: 120000,
    status: 'Visszaigazolva'
  },
  {
    id: 'ven-3',
    code: 'BOR-03',
    name: 'Alasz Pince & Borterasz',
    category: 'Borászat (Fő tér)',
    location: 'Fő tér 3. pavilon',
    contact: 'Alasz Pál',
    phone: '+36 30 444 3322',
    power: '1x16A (Hűtőkhöz)',
    water: false,
    trashBins: 1,
    trashBagsIssued: 6,
    deposit: 50000,
    fee: 120000,
    status: 'Visszaigazolva'
  },
  {
    id: 'ven-4',
    code: 'BOR-04',
    name: 'Láng Pincészet Kőszegdoroszló',
    category: 'Borászat (Fő tér)',
    location: 'Fő tér 4. pavilon',
    contact: 'Láng József',
    phone: '+36 30 555 4433',
    power: '1x16A',
    water: false,
    trashBins: 1,
    trashBagsIssued: 6,
    deposit: 50000,
    fee: 120000,
    status: 'Visszaigazolva'
  },

  // JURISICS TÉR - ÉTELEK UTCÁJA
  {
    id: 'ven-5',
    code: 'GASZT-01',
    name: 'Kőszegi Ínyenc Lángos & Grill',
    category: 'Ételek utcája (Jurisics tér)',
    location: 'Jurisics tér - Városháza előtt',
    contact: 'Varga Béla',
    phone: '+36 70 123 4567',
    power: '3x32A Ipari (Fritőz + rostlap)',
    water: true,
    trashBins: 2,
    trashBagsIssued: 15,
    deposit: 80000,
    fee: 220000,
    status: 'Visszaigazolva'
  },
  {
    id: 'ven-6',
    code: 'GASZT-02',
    name: 'Várkapu Burger & Pulled Pork Truck',
    category: 'Ételek utcája (Jurisics tér)',
    location: 'Jurisics tér - Hősök tornya mellett',
    contact: 'Horváth Tamás',
    phone: '+36 30 666 7788',
    power: '3x32A Ipari (Sütők)',
    water: true,
    trashBins: 2,
    trashBagsIssued: 15,
    deposit: 80000,
    fee: 220000,
    status: 'Visszaigazolva'
  },
  {
    id: 'ven-7',
    code: 'GASZT-03',
    name: 'Kürtőskalács & Rétes Házikó',
    category: 'Ételek utcája (Jurisics tér)',
    location: 'Jurisics tér - Szökőkút mellett',
    contact: 'Szabó Éva',
    phone: '+36 20 777 8899',
    power: '3x16A (Sütőfa melegítő)',
    water: false,
    trashBins: 1,
    trashBagsIssued: 8,
    deposit: 50000,
    fee: 140000,
    status: 'Visszaigazolva'
  },
  {
    id: 'ven-8',
    code: 'GASZT-04',
    name: 'Kézműves Sörök Udvara',
    category: 'Ételek utcája (Jurisics tér)',
    location: 'Jurisics tér - Tábornokház sarok',
    contact: 'Molnár Dániel',
    phone: '+36 30 888 9900',
    power: '1x16A (Sörcsap hűtők)',
    water: true,
    trashBins: 2,
    trashBagsIssued: 12,
    deposit: 60000,
    fee: 180000,
    status: 'Visszaigazolva'
  }
];

export const INITIAL_TASKS = [
  {
    id: 'tsk-1',
    title: 'Kőszegi Polgármesteri Hivatal csendrendelet & zajkibocsátási felmentés benyújtása (Várdisco péntek 02:00!)',
    category: 'Engedélyek & Hatóság',
    priority: 'Sürgős',
    assignedTo: 'Gábor',
    dueDate: '2026-05-02',
    completed: true,
    completedBy: 'Gábor',
    completedAt: '2026-04-18 10:45',
    createdBy: 'Szilveszter',
    notes: 'Kérelem a jegyzőhöz benyújtva, jóváhagyva a pénteki 02:00 zárásra.'
  },
  {
    id: 'tsk-2',
    title: 'Nagyszínpad 10x8m fedés & Line Array hangrendszer szerződés véglegesítése',
    category: 'Technika & Áram',
    priority: 'Sürgős',
    assignedTo: 'Szilveszter',
    dueDate: '2026-05-05',
    completed: true,
    completedBy: 'Szilveszter',
    completedAt: '2026-04-20 14:12',
    createdBy: 'Szilveszter',
    notes: 'Stage Pro Kft. visszaigazolta a pünkösdi hétvégét.'
  },
  {
    id: 'tsk-3',
    title: 'Ocho Macho szerződés aláírása és 50% előleg átutalásának indítása',
    category: 'Nagyszínpad',
    priority: 'Sürgős',
    assignedTo: 'Zoltán',
    dueDate: '2026-05-08',
    completed: true,
    completedBy: 'Zoltán',
    completedAt: '2026-04-22 16:30',
    createdBy: 'Szilveszter',
    notes: 'Előleg számla beérkezett, átutalás teljesítve.'
  },
  {
    id: 'tsk-4',
    title: 'E.ON és Városüzemeltetés egyeztetés az ideiglenes mérőhelyekről a Fő téren és Jurisics téren',
    category: 'Technika & Áram',
    priority: 'Magas',
    assignedTo: 'Műszaki Stáb',
    dueDate: '2026-05-10',
    completed: false,
    completedBy: null,
    completedAt: null,
    createdBy: 'Szilveszter',
    notes: 'Gasztrósoknak 3x32A betáp pontok ellenőrzése'
  },
  {
    id: 'tsk-5',
    title: '120L extra erős szemeteszsákok (40 tekercs) és 20 db kukaállvány beérkezése a KTSZE raktárba',
    category: 'Higiénia & Szemét',
    priority: 'Magas',
    assignedTo: 'Önkéntes Csapat',
    dueDate: '2026-05-12',
    completed: false,
    completedBy: null,
    completedAt: null,
    createdBy: 'Szilveszter',
    notes: 'Azonosító matricák felragasztása (ZSAK-001..040)'
  },
  {
    id: 'tsk-6',
    title: '12 db mobil WC (ebből 2 akadálymentes) és 4 kézmosó pont megrendelése napi 2x szippantással',
    category: 'Higiénia & Szemét',
    priority: 'Magas',
    assignedTo: 'Szilveszter',
    dueDate: '2026-05-14',
    completed: false,
    completedBy: null,
    completedAt: null,
    createdBy: 'Szilveszter',
    notes: 'ToiToi partner visszaigazolása szükséges'
  },
  {
    id: 'tsk-7',
    title: 'Orvosi mentőügyelet (mentőautó + orvos) és felelősségbiztosítás szerződés megkötése',
    category: 'Engedélyek & Hatóság',
    priority: 'Magas',
    assignedTo: 'Gábor',
    dueDate: '2026-05-15',
    completed: false,
    completedBy: null,
    completedAt: null,
    createdBy: 'Gábor',
    notes: 'Mentőszolgálat árajánlat megérkezett'
  },
  {
    id: 'tsk-8',
    title: 'Artisjus zenei dallisták (Tracklist) bekérése a fellépőktől és bejelentő ív kitöltése',
    category: 'Pályázat & Admin',
    priority: 'Normál',
    assignedTo: 'Szilveszter',
    dueDate: '2026-05-18',
    completed: false,
    completedBy: null,
    completedAt: null,
    createdBy: 'Szilveszter',
    notes: 'Besh o droM, Bohemian Betyars már beküldte'
  },
  {
    id: 'tsk-9',
    title: 'Backstage catering és ásványvíz (15 tálca) kiszállítása a nagyszínpad öltözősátrába',
    category: 'Nagyszínpad',
    priority: 'Magas',
    assignedTo: 'Önkéntes Csapat',
    dueDate: '2026-05-22',
    completed: false,
    completedBy: null,
    completedAt: null,
    createdBy: 'Szilveszter',
    notes: 'Hűtőszekrény bekapcsolása péntek 10:00-ig'
  },
  {
    id: 'tsk-10',
    title: 'Utcazenész kapualjak és kérések ellenőrzése: asztalok, 20m hosszabbítók kiszállítása',
    category: 'Technika & Áram',
    priority: 'Normál',
    assignedTo: 'Műszaki Stáb',
    dueDate: '2026-05-22',
    completed: false,
    completedBy: null,
    completedAt: null,
    createdBy: 'Szilveszter',
    notes: 'Hősök kapuja alatti és Várárok zenészek'
  }
];

export const INITIAL_INVENTORY = [
  // HIGIÉNIA & SZEMETESZSÁKOK
  { id: 'inv-1', code: 'ZSAK-001..010', name: '120L Extra Erős Szemeteszsákok (Kék Kommunális)', category: 'Higiénia & Szemét', qty: 10, unit: 'tekercs (250db)', location: 'Fő tér boros faházak', responsible: 'Önkéntes Csapat', status: 'Kiadva' },
  { id: 'inv-2', code: 'ZSAK-011..020', name: '120L Extra Erős Szemeteszsákok (Sárga Műanyag)', category: 'Higiénia & Szemét', qty: 10, unit: 'tekercs (250db)', location: 'Jurisics tér Ételek utcája', responsible: 'Önkéntes Csapat', status: 'Kiadva' },
  { id: 'inv-3', code: 'ZSAK-021..030', name: '120L Fekete Zsákok (Nagyszínpad & Backstage)', category: 'Higiénia & Szemét', qty: 10, unit: 'tekercs (250db)', location: 'Fő tér Backstage sátor', responsible: 'Szilveszter', status: 'Raktáron' },
  { id: 'inv-4', code: 'ZSAK-031..040', name: '120L Tartalék Szemeteszsák készlet', category: 'Higiénia & Szemét', qty: 10, unit: 'tekercs (250db)', location: 'KTSZE Raktár', responsible: 'Önkéntes Csapat', status: 'Raktáron' },
  { id: 'inv-5', code: 'KUKA-01..10', name: '120L Mobil Kukaállványok szelektív fedéllel', category: 'Higiénia & Szemét', qty: 10, unit: 'db', location: 'Fő tér sétány', responsible: 'Műszaki Stáb', status: 'Telepítve' },
  { id: 'inv-6', code: 'KUKA-11..20', name: '240L Zöld Hulladékgyűjtő konténer', category: 'Higiénia & Szemét', qty: 10, unit: 'db', location: 'Jurisics tér sarok', responsible: 'Műszaki Stáb', status: 'Telepítve' },

  // ÁRAM & KÁBEL
  { id: 'inv-7', code: 'KABEL-01', name: '63A Ipari Főkábel 25m (Nagyszínpad betáp)', category: 'Áram & Kábel', qty: 1, unit: 'db', location: 'Fő tér villanyóra', responsible: 'Műszaki Stáb', status: 'Használatban' },
  { id: 'inv-8', code: 'KABEL-02..05', name: '32A Ipari Elosztódobozok 4x230V kimenettel', category: 'Áram & Kábel', qty: 4, unit: 'db', location: 'Jurisics tér Gasztro', responsible: 'Műszaki Stáb', status: 'Kiadva' },
  { id: 'inv-9', code: 'KABEL-06..15', name: '20m Kültéri Gumi Hosszabbítók (Kapualjakhoz)', category: 'Áram & Kábel', qty: 10, unit: 'db', location: 'Utcazenész pontok', responsible: 'Szilveszter', status: 'Kiadva' },
  { id: 'inv-10', code: 'TAPOS-01..20', name: 'Sárga-fekete Gumi Kábelátvezetők (1m/db)', category: 'Áram & Kábel', qty: 20, unit: 'méter', location: 'Fő tér gyalogos sáv', responsible: 'Műszaki Stáb', status: 'Telepítve' },

  // KORDONOK & VÉDELEM
  { id: 'inv-11', code: 'KORD-01..15', name: 'Mojo Alumínium Taposókordon (Nagyszínpad elé)', category: 'Kordon & Védelem', qty: 15, unit: 'db (30m)', location: 'Fő tér Nagyszínpad', responsible: 'Szilveszter', status: 'Raktáron' },
  { id: 'inv-12', code: 'KORD-16..40', name: 'Mobil Fesztivál Kordonok (Backstage lezárás)', category: 'Kordon & Védelem', qty: 25, unit: 'db (50m)', location: 'Backstage & Színpad hátul', responsible: 'Műszaki Stáb', status: 'Telepítve' },
  
  // BÚTOR & SÁTOR
  { id: 'inv-13', code: 'SATO-01', name: 'Nagyszínpad Öltözősátor 6x4m (zárható, ablakos)', category: 'Színpad & Bútor', qty: 1, unit: 'db', location: 'Fő tér színpad mögött', responsible: 'Szilveszter', status: 'Raktáron' },
  { id: 'inv-14', code: 'SÖRP-01..15', name: 'Sörpad garnitúrák (1 asztal + 2 pad)', category: 'Színpad & Bútor', qty: 15, unit: 'garnitúra', location: 'Backstage & Infópont', responsible: 'Önkéntes Csapat', status: 'Raktáron' },
  
  // BIZTONSÁG & MENTÉS
  { id: 'inv-15', code: 'TUZ-01..08', name: '6kg ABC Hitelesített Poroltó Készülék', category: 'Biztonság & Mentés', qty: 8, unit: 'db', location: 'Színpadok & Gasztro bódék', responsible: 'Gábor', status: 'Ellenőrizve' }
];

export const INITIAL_TRACKLIST = [
  { id: 'trk-1', artist: 'Besh o droM', order: 1, title: 'Kecskemét', composers: 'Pettik Ádám, Barcza Gergely', lyricists: 'Tradicionális gyűjtés', duration: '04:15', type: 'Feldolgozás', reported: true },
  { id: 'trk-2', artist: 'Besh o droM', order: 2, title: 'Meggyújtom a pipám', composers: 'Pettik Ádám', lyricists: 'Barcza Gergely', duration: '03:50', type: 'Saját szerzemény', reported: true },
  { id: 'trk-3', artist: 'Bohemian Betyars', order: 1, title: 'Megjöttek a fiúk', composers: 'Szűcs Levente, Palágyi Máté', lyricists: 'Szűcs Levente', duration: '03:40', type: 'Saját szerzemény', reported: true },
  { id: 'trk-4', artist: 'Bohemian Betyars', order: 2, title: 'Összefúj a szél', composers: 'Szűcs Levente', lyricists: 'Szűcs Levente', duration: '04:05', type: 'Saját szerzemény', reported: true },
  { id: 'trk-5', artist: 'Ocho Macho', order: 1, title: 'Jó nekem', composers: 'Kirchknopf Gergő, Csík András', lyricists: 'Kirchknopf Gergő', duration: '03:55', type: 'Saját szerzemény', reported: true },
  { id: 'trk-6', artist: 'Ocho Macho', order: 2, title: 'Pancho', composers: 'Ocho Macho zenekar', lyricists: 'Kirchknopf Gergő', duration: '04:20', type: 'Saját szerzemény', reported: true },
  { id: 'trk-7', artist: 'Söndörgő', order: 1, title: 'Jozo', composers: 'Eredics Áron, Eredics Benjamin', lyricists: 'Tradicionális balkán', duration: '05:10', type: 'Feldolgozás', reported: true },
  { id: 'trk-8', artist: 'Parno Graszt', order: 1, title: 'Készpénz', composers: 'Oláh József', lyricists: 'Oláh József', duration: '03:55', type: 'Saját szerzemény', reported: false },
  { id: 'trk-9', artist: 'Romengo', order: 1, title: 'Kétháné', composers: 'Rostás Mihály Mazsi', lyricists: 'Lakatos Mónika', duration: '04:45', type: 'Saját szerzemény', reported: true }
];

export const INITIAL_BUDGET = [
  { id: 'bgt-1', code: 'TEC-01', category: 'Színpad- és Hangtechnika', name: 'Fedett Nagyszínpad 10x8m, Line Array hang- és robotlámpa fénystábbal (3 nap)', qty: 1, unit: 'komplett', unitPrice: 3900000, grant: 3200000, own: 700000, supplier: 'Stage Pro Hungary Kft.', invoice: 'SPH-2026/041', status: 'Megrendelve' },
  { id: 'bgt-2', code: 'TEC-02', category: 'Színpad- és Hangtechnika', name: 'Kisszínpadok (2 db) és Kapualj akusztikus PA szettek bérlése', qty: 2, unit: 'szett', unitPrice: 450000, grant: 720000, own: 180000, supplier: 'Sound & Light Bt.', invoice: '-', status: 'Tervezett' },
  { id: 'bgt-3', code: 'ART-01', category: 'Fellépői Tiszteletdíjak', name: 'Nagyszínpadi élőkoncertek gázsija (Ocho Macho, Besh o droM, Bohemian Betyars, Parno Graszt)', qty: 1, unit: 'összes', unitPrice: 7450000, grant: 6200000, own: 1250000, supplier: 'Zenekari számlák', invoice: '-', status: 'Szerződés alatt' },
  { id: 'bgt-4', code: 'ART-02', category: 'Fellépői Tiszteletdíjak', name: 'Várdisco fellépők (TornyosiGabi, Kunyik, Magnus, Tisztafaxxa) tiszteletdíja', qty: 1, unit: 'est', unitPrice: 350000, grant: 250000, own: 100000, supplier: 'KTSZE Elszámolás', invoice: '-', status: 'Jóváhagyva' },
  { id: 'bgt-5', code: 'ART-03', category: 'Fellépői Tiszteletdíjak', name: 'Vasárnapi sztárfellépő (G.w.M / Majka) keretösszeg', qty: 1, unit: 'koncert', unitPrice: 3200000, grant: 2700000, own: 500000, supplier: 'Menedzsment Kft.', invoice: '-', status: 'Egyeztetés alatt' },
  { id: 'bgt-6', code: 'ART-04', category: 'Fellépői Tiszteletdíjak', name: 'Utcazenészek díjazása és gyerekműsorok fellépői tiszteletdíjai', qty: 1, unit: 'keret', unitPrice: 950000, grant: 800000, own: 150000, supplier: 'Egyesületi kifizetés', invoice: '-', status: 'Jóváhagyva' },
  { id: 'bgt-7', code: 'HUG-01', category: 'Higiénia és Hulladékkezelés', name: '12 db Mobil WC (2 akadálymentes) + 4 kézmosó bérlése és napi 2x szervize', qty: 1, unit: 'hétvége', unitPrice: 670000, grant: 550000, own: 120000, supplier: 'ToiToi Magyarország', invoice: '-', status: 'Ajánlatkérés beérkezett' },
  { id: 'bgt-8', code: 'HUG-02', category: 'Higiénia és Hulladékkezelés', name: '120L szemeteszsákok (40 tekercs), kukaállványok, takarítószerek', qty: 40, unit: 'tekercs', unitPrice: 3500, grant: 120000, own: 20000, supplier: 'Kőszegi Beszerzés', invoice: '-', status: 'Tervezett' },
  { id: 'bgt-9', code: 'HUG-03', category: 'Higiénia és Hulladékkezelés', name: 'Fesztivál takarító személyzet (4 fő x 4 nap) és konténeres elszállítás', qty: 1, unit: 'csomag', unitPrice: 480000, grant: 400000, own: 80000, supplier: 'Kőszegi Városüzemeltetés', invoice: '-', status: 'Egyeztetve' },
  { id: 'bgt-10', code: 'SEC-01', category: 'Biztonság és Engedélyek', name: 'Vagyonőri biztosítás 24 órában (Fő tér, színpadok, kordonok) 6 fő', qty: 4, unit: 'nap', unitPrice: 160000, grant: 500000, own: 140000, supplier: 'Őrző-védő Kft.', invoice: '-', status: 'Szerződés alatt' },
  { id: 'bgt-11', code: 'SEC-02', category: 'Biztonság és Engedélyek', name: 'Orvosi mentőügyelet mentőautóval (napi 12 óra kötelező jelenlét)', qty: 4, unit: 'nap', unitPrice: 140000, grant: 450000, own: 110000, supplier: 'Mentőszolgálat', invoice: '-', status: 'Ajánlatkérés elküldve' },
  { id: 'bgt-12', code: 'SEC-03', category: 'Biztonság és Engedélyek', name: 'Artisjus szerzői jogdíjak megváltása (pályázati elszámolható tétel)', qty: 1, unit: 'átalány', unitPrice: 620000, grant: 550000, own: 70000, supplier: 'Artisjus', invoice: '-', status: 'Tervezett' },
  { id: 'bgt-13', code: 'MKT-01', category: 'Marketing és Nyomda', name: 'Plakátok (B1 250db), programfüzet (3000db), molinók, karszalagok, Meta ads', qty: 1, unit: 'kampány', unitPrice: 980000, grant: 850000, own: 130000, supplier: 'Kőszegi Nyomda & Grafika', invoice: '-', status: 'Gyártás alatt' },
  { id: 'bgt-14', code: 'INF-01', category: 'Infrastruktúra és Áram', name: 'Ideiglenes áramhálózat kiépítése (Fő tér + Jurisics tér gasztro betápok)', qty: 1, unit: 'projekt', unitPrice: 420000, grant: 350000, own: 70000, supplier: 'Regisztrált Villanyszerelő', invoice: '-', status: 'Folyamatban' },
  { id: 'bgt-15', code: 'RES-01', category: 'Tartalékkeret', name: 'Előre nem látható műszaki és helyszíni tartalékkeret (5%)', qty: 1, unit: 'keret', unitPrice: 1000000, grant: 500000, own: 500000, supplier: 'KTSZE Belső', invoice: '-', status: 'Jóváhagyva' }
];

export const INITIAL_LOGS = [
  { id: 'log-1', user: 'Szilveszter', action: 'CREATE', module: 'Nagyszínpad', description: 'Felvette a péntek esti VÁRDISCO blokkot: Kunyik, Magnus, TornyosiGabi, TISZTAFAXXA', time: '2026-04-18 09:15' },
  { id: 'log-2', user: 'Gábor', action: 'COMPLETE_TASK', module: 'To-Do', description: 'Kipipálta a polgármesteri csendrendelet felmentési kérelmet', time: '2026-04-18 10:45' },
  { id: 'log-3', user: 'Szilveszter', action: 'COMPLETE_TASK', module: 'To-Do', description: 'Kipipálta a nagyszínpad és Line Array hangtechnika szerződést', time: '2026-04-20 14:12' },
  { id: 'log-4', user: 'Zoltán', action: 'COMPLETE_TASK', module: 'To-Do', description: 'Kipipálta az Ocho Macho 50% előleg átutalását', time: '2026-04-22 16:30' },
  { id: 'log-5', user: 'Szilveszter', action: 'UPDATE', module: 'Árusok', description: 'Módosította a GASZT-01 (Kőszegi Lángos) áramigényét 3x32A Ipari-ra', time: '2026-04-23 11:20' }
];

export const INITIAL_CONTRACTORS = [
  {
    id: 'cnt-1',
    code: 'SZOLG-01',
    companyName: 'Stage Pro Hungary Kft.',
    category: 'Színpad- és Hangtechnika',
    service: '10x8m fedett nagyszínpad építése, Line Array hangrendszer, DMX robotlámpák, 4 fős technikus stáb (3 nap)',
    contactName: 'Kovács Péter (Műszaki ig.)',
    phone: '+36 30 911 2233',
    email: 'info@stageprohungary.hu',
    feeHuf: 3900000,
    contractStatus: 'Aláírva',
    paymentStatus: 'Előleg kifizetve (50%)',
    invoiceNumber: 'SPH-2026/041',
    contractDoc: 'Stage_Pro_Szerzodes_2026_KTSZE.pdf',
    quoteDoc: 'Stage_Pro_Arajanlat_Vegleges.pdf',
    completionDoc: 'Stage_Pro_Előleg_Szamla_041.pdf',
    notes: 'Kiszállás és építés: Csütörtök 08:00-tól a Fő téren!'
  },
  {
    id: 'cnt-2',
    code: 'SZOLG-02',
    companyName: 'Kőszegi Városüzemeltetés & Kommunális Kft.',
    category: 'Kukás & Hulladékkezelés',
    service: 'Konténeres hulladékszállítás (2 db 10m3 konténer), napi kétszeri ürítés, közterületi takarítás és lerakási díj',
    contactName: 'Németh László',
    phone: '+36 94 360 120',
    email: 'hulladek@koszegikozuzem.hu',
    feeHuf: 480000,
    contractStatus: 'Aláírva',
    paymentStatus: 'Fizetésre vár',
    invoiceNumber: 'KKK-2026/019',
    contractDoc: 'Koszeg_Kommunalis_Hulladek_Megallapodas.pdf',
    quoteDoc: 'Kontener_Kalkulacio_2026.pdf',
    completionDoc: null,
    notes: 'Konténerek elhelyezése a Jurisics tér mögötti parkolóban'
  },
  {
    id: 'cnt-3',
    code: 'SZOLG-03',
    companyName: 'Savaria Elektrik & Hálózatépítő Kft.',
    category: 'Villanyszerelő & E.ON',
    service: 'Ideiglenes áramvételezési pontok kiépítése (Fő tér + Jurisics tér), mérőhelyek, 63A/32A elosztók felügyelete',
    contactName: 'Bognár Zoltán (Regisztrált villanyszerelő)',
    phone: '+36 30 789 4512',
    email: 'savaria.elektrik@gmail.com',
    feeHuf: 420000,
    contractStatus: 'Aláírva',
    paymentStatus: 'Fizetésre vár',
    invoiceNumber: 'SE-2026/112',
    contractDoc: 'Savaria_Elektrik_Kivitelezesi_Szerzodes.pdf',
    quoteDoc: 'Villamos_Munka_Koltsegvetes.pdf',
    completionDoc: null,
    notes: 'E.ON bekapcsolás péntek 10:00-ra készen kell lennie!'
  },
  {
    id: 'cnt-4',
    code: 'SZOLG-04',
    companyName: 'Országos Mentőszolgálat / Rescue Med Kft.',
    category: 'Mentőszolgálat & Egészségügy',
    service: 'Kitelepült mentőautó orvossal és szakápolóval napi 12 órában (Péntek-Hétfő), elsősegély állomás',
    contactName: 'Dr. Szabó Gábor',
    phone: '+36 20 445 6677',
    email: 'ugyelet@rescuemed.hu',
    feeHuf: 560000,
    contractStatus: 'Kiküldve',
    paymentStatus: 'Fizetésre vár',
    invoiceNumber: '-',
    contractDoc: 'OMSZ_Kitelepules_Szerzodestervezet.pdf',
    quoteDoc: 'Mentoallomas_Ugyelet_Arajánlat.pdf',
    completionDoc: null,
    notes: 'Mentőautó bázisa a Városháza udvarán kijelölt behajtóval'
  },
  {
    id: 'cnt-5',
    code: 'SZOLG-05',
    companyName: 'Jurisics Security & Vagyonvédelem Kft.',
    category: 'Biztonsági Szolgálat & Őrzés',
    service: '24 órás helyszíni őrzés (Fő tér nagyszínpad, backstage, kordonok, éjszakai technika őrzés) 6 fő x 4 nap',
    contactName: 'Varga Tamás (Biztonsági vezető)',
    phone: '+36 30 555 9988',
    email: 'security@jurisics.hu',
    feeHuf: 640000,
    contractStatus: 'Aláírva',
    paymentStatus: 'Előleg kifizetve (30%)',
    invoiceNumber: 'JS-2026/088',
    contractDoc: 'Jurisics_Security_Orzesi_Megbizas.pdf',
    quoteDoc: 'Biztonsagi_Terv_es_Arajánlat.pdf',
    completionDoc: 'Security_Előleg_Szamla_088.pdf',
    notes: 'Péntek esti Várdisconál +2 fő kordonos megerősítés!'
  },
  {
    id: 'cnt-6',
    code: 'SZOLG-06',
    companyName: 'Toi Toi & Dixi Sanitär Kft.',
    category: 'Mobil WC & Higiénia',
    service: '12 db mobil WC (ebből 2 mozgássérült akadálymentes), 4 kézmosó állomás, napi kétszeri szippantás és vegyszerezés',
    contactName: 'Horváth Andrea',
    phone: '+36 1 456 7890',
    email: 'rendeles@toitoi.hu',
    feeHuf: 670000,
    contractStatus: 'Aláírva',
    paymentStatus: 'Fizetésre vár',
    invoiceNumber: 'TT-2026/4512',
    contractDoc: 'ToiToi_Berleti_Szerzodes_2026.pdf',
    quoteDoc: 'ToiToi_Mobil_Higienia_Arajánlat.pdf',
    completionDoc: null,
    notes: 'Telepítés csütörtök délután, elszállítás kedd reggel'
  },
  {
    id: 'cnt-7',
    code: 'SZOLG-07',
    companyName: 'Power Rent Aggregátor Kft.',
    category: 'Aggregátor & Tartalék Áram',
    service: '60 kVA Csendesített dízel aggregátor biztonsági tartaléknak + 200L dízel üzemanyag',
    contactName: 'Kiss Mihály',
    phone: '+36 70 333 8811',
    email: 'berles@powerrent.hu',
    feeHuf: 320000,
    contractStatus: 'Tárgyalás alatt',
    paymentStatus: 'Fizetésre vár',
    invoiceNumber: '-',
    contractDoc: null,
    quoteDoc: 'Power_Rent_Aggregator_Arajanlat.pdf',
    completionDoc: null,
    notes: 'Áramkimaradás esetén automatikus átkapcsolóval'
  },
  {
    id: 'cnt-8',
    code: 'SZOLG-08',
    companyName: 'Kőszegi Nyomda & Grafikai Stúdió',
    category: 'Nyomda & Reklámfelület',
    service: 'B1/B2 plakátok (250 db), 3000 db színes hajtott programfüzet, színpad háttérmolinó (8x4m), 1500 db szövet karszalag',
    contactName: 'Takács Krisztina',
    phone: '+36 94 560 300',
    email: 'nyomda@koszegprint.hu',
    feeHuf: 980000,
    contractStatus: 'Aláírva',
    paymentStatus: 'Előleg kifizetve (50%)',
    invoiceNumber: 'KNY-2026/092',
    contractDoc: 'Koszeg_Nyomda_Gyartasi_Megallapodas.pdf',
    quoteDoc: 'Nyomdai_Kalkulacio_Molinok_Karszalag.pdf',
    completionDoc: 'Nyomda_Előleg_Szamla_092.pdf',
    notes: 'Kész anyagok átvétele május 15-ig!'
  },
  {
    id: 'cnt-9',
    code: 'SZOLG-09',
    companyName: 'Event Racks & Sátor Kft.',
    category: 'Kordonok & Sátorbérlés',
    service: 'Mojo taposókordon (30m nagyszínpad elé), 80m kordon backstage lezáráshoz, 2 db 6x4m öltözősátor',
    contactName: 'Farkas Dániel',
    phone: '+36 30 667 8901',
    email: 'berles@eventsator.hu',
    feeHuf: 470000,
    contractStatus: 'Aláírva',
    paymentStatus: 'Fizetésre vár',
    invoiceNumber: 'ER-2026/304',
    contractDoc: 'Event_Racks_Kordon_Sator_Szerzodes.pdf',
    quoteDoc: 'Kordon_Sator_Arajanlat.pdf',
    completionDoc: null,
    notes: 'Szállítás csütörtök 14:00'
  },
  {
    id: 'cnt-10',
    code: 'SZOLG-10',
    companyName: 'Generali Biztosító Zrt.',
    category: 'Felelősségbiztosítás',
    service: '3 napos Fesztivál Felelősségbiztosítási kötvény (dologi és személyi károkra 50 millió Ft-ig)',
    contactName: 'Molnár Judit',
    phone: '+36 30 112 3344',
    email: 'rendezveny@generali.hu',
    feeHuf: 140000,
    contractStatus: 'Aláírva',
    paymentStatus: 'Kifizetve',
    contractDoc: 'Generali_Fesztival_Biztositas_Kotveny.pdf',
    quoteDoc: 'Biztositas_Ajanlat_KTSZE.pdf',
    completionDoc: 'Generali_Szamla_Kifizetve.pdf',
    notes: 'Kötvény száma: FESZT-2026-KOSZEG-01'
  }
];

export const MAP_ZONES = [
  { id: 'zone-fo-ter', name: 'Fő tér — Borok Helyszíne & Nagyszínpad', color: '#3b82f6', bg: '#1e3a8a' },
  { id: 'zone-jurisics', name: 'Jurisics tér — Ételek Utcája & Kisszínpad 1', color: '#f59e0b', bg: '#78350f' },
  { id: 'zone-var', name: 'Várjátszótér & Várárok — Gyerekbirodalom', color: '#10b981', bg: '#064e3b' },
  { id: 'zone-kapualj', name: 'Belvárosi Kapualjak — Utcazenei Pontok', color: '#8b5cf6', bg: '#4c1d95' }
];

export const MAP_POINTS = [
  // FŐ TÉR
  { id: 'pt-nsz', zoneId: 'zone-fo-ter', code: 'NAGYSZÍNPAD', name: 'Nagyszínpad 10x8m Fedett', type: 'stage', x: 28, y: 22, power: '63A Ipari', contact: 'Szilveszter (+36 30 123 4567)', status: 'Üzemkész', hasProblem: false, problemText: '' },
  { id: 'pt-back', zoneId: 'zone-fo-ter', code: 'BACKSTAGE', name: 'Nagyszínpad Öltözősátor & Zóna', type: 'backstage', x: 18, y: 18, power: '1x16A', contact: 'Szilveszter', status: 'Zárt VIP', hasProblem: false, problemText: '' },
  { id: 'pt-el-1', zoneId: 'zone-fo-ter', code: 'ÁRAM-01', name: 'Fő tér Központi Villamos Szekrény & E.ON Mérő', type: 'power', x: 22, y: 35, power: '125A Főbetáp', contact: 'Bognár Zoltán Vill. (+36 30 789 4512)', status: 'Bekapcsolva', hasProblem: false, problemText: '' },
  { id: 'pt-mento', zoneId: 'zone-fo-ter', code: 'MENTŐ-01', name: 'Orvosi Ügyelet & Rohammentő Bázis', type: 'medical', x: 12, y: 45, power: '230V', contact: 'OMSZ Ügyelet (+36 20 445 6677)', status: 'Készenlétben', hasProblem: false, problemText: '' },
  { id: 'pt-info', zoneId: 'zone-fo-ter', code: 'INFO-KTSZE', name: 'KTSZE Információs Sátor & Karszalag Pont', type: 'info', x: 42, y: 48, power: '1x16A', contact: 'Gábor Elnök', status: 'Nyitva', hasProblem: false, problemText: '' },
  { id: 'pt-wc-1', zoneId: 'zone-fo-ter', code: 'TOI-FŐTÉR', name: 'Fő tér Mobil WC Sziget (6 db + 1 Kerekesszékes)', type: 'toilet', x: 14, y: 65, power: '-', contact: 'ToiToi Ügyelet', status: 'Tiszta / Üzemel', hasProblem: false, problemText: '' },
  
  // BOROK FAHÁZAI (FŐ TÉR)
  { id: 'pt-bor-1', zoneId: 'zone-fo-ter', code: 'BOR-01', name: 'Stefanich Pincészet Kőszeg', type: 'wine', x: 50, y: 22, power: '1x16A', contact: 'Stefanich Zoltán (+36 30 222 1100)', status: 'Üzemel', trashBags: 6, hasProblem: false, problemText: '' },
  { id: 'pt-bor-2', zoneId: 'zone-fo-ter', code: 'BOR-02', name: 'Tóth Pincészet Kőszeg', type: 'wine', x: 62, y: 22, power: '1x16A', contact: 'Tóth Ferenc (+36 30 333 2211)', status: 'Üzemel', trashBags: 6, hasProblem: false, problemText: '' },
  { id: 'pt-bor-3', zoneId: 'zone-fo-ter', code: 'BOR-03', name: 'Alasz Pince & Borterasz', type: 'wine', x: 74, y: 22, power: '1x16A', contact: 'Alasz Pál (+36 30 444 3322)', status: 'Üzemel', trashBags: 6, hasProblem: false, problemText: '' },
  { id: 'pt-bor-4', zoneId: 'zone-fo-ter', code: 'BOR-04', name: 'Láng Pincészet Kőszegdoroszló', type: 'wine', x: 86, y: 22, power: '1x16A', contact: 'Láng József (+36 30 555 4433)', status: 'Zsákhiány!', trashBags: 6, hasProblem: true, problemText: 'Kifogyott a 120L szemeteszsák, 2 tekercs azonnal kell!' },
  { id: 'pt-bor-5', zoneId: 'zone-fo-ter', code: 'BOR-05', name: 'Jagodics Pincészet', type: 'wine', x: 50, y: 38, power: '1x16A', contact: 'Jagodics Attila', status: 'Üzemel', trashBags: 6, hasProblem: false, problemText: '' },
  { id: 'pt-bor-6', zoneId: 'zone-fo-ter', code: 'BOR-06', name: 'Kampits Családi Pince', type: 'wine', x: 62, y: 38, power: '1x16A', contact: 'Kampits Tibor', status: 'Üzemel', trashBags: 6, hasProblem: false, problemText: '' },
  { id: 'pt-bor-7', zoneId: 'zone-fo-ter', code: 'BOR-07', name: 'Mándli Kőszegi Borászat', type: 'wine', x: 74, y: 38, power: '1x16A', contact: 'Mándli Tibor', status: 'Üzemel', trashBags: 6, hasProblem: false, problemText: '' },
  { id: 'pt-bor-8', zoneId: 'zone-fo-ter', code: 'BOR-08', name: 'Frank Kőszegi Borház', type: 'wine', x: 86, y: 38, power: '1x16A', contact: 'Frank János', status: 'Üzemel', trashBags: 6, hasProblem: false, problemText: '' },

  // JURISICS TÉR — ÉTELEK UTCÁJA
  { id: 'pt-ksz-1', zoneId: 'zone-jurisics', code: 'KISSZÍNPAD-1', name: 'Kisszínpad 1 (Jurisics tér - Szökőkút)', type: 'stage', x: 30, y: 72, power: '32A Ipari', contact: 'Önkéntes Csapat', status: 'Aktív Műsor', hasProblem: false, problemText: '' },
  { id: 'pt-el-2', zoneId: 'zone-jurisics', code: 'ÁRAM-02', name: 'Jurisics tér Ipari 3x32A Gasztro Elosztó', type: 'power', x: 48, y: 68, power: '3x63A Főbetáp', contact: 'Villanyszerelő stáb', status: 'Fokozott terhelés', hasProblem: false, problemText: '' },
  { id: 'pt-viz-1', zoneId: 'zone-jurisics', code: 'VÍZ-01', name: 'Központi Vízvételezés és Szennyvíz Csatlakozás', type: 'water', x: 58, y: 68, power: '-', contact: 'Városüzemeltetés', status: 'Nyomás rendben', hasProblem: false, problemText: '' },
  { id: 'pt-kont', zoneId: 'zone-jurisics', code: 'KONTÉNER', name: '2 db 10m3 Zárt Hulladéktömörítő Konténer', type: 'waste', x: 18, y: 88, power: '-', contact: 'Kőszegi Kommunális', status: 'Ürítés reggel', hasProblem: false, problemText: '' },
  { id: 'pt-wc-2', zoneId: 'zone-jurisics', code: 'TOI-JURISICS', name: 'Jurisics tér Mobil WC Sziget (6 db ToiToi)', type: 'toilet', x: 88, y: 88, power: '-', contact: 'ToiToi Ügyelet', status: 'Tiszta', hasProblem: false, problemText: '' },

  // FOOD TRUCKS & KAJÁSOK (JURISICS TÉR)
  { id: 'pt-g-1', zoneId: 'zone-jurisics', code: 'GASZT-01', name: 'Kőszegi Ínyenc Lángos & Grill', type: 'food', x: 42, y: 82, power: '3x32A Ipari', contact: 'Varga Béla (+36 70 123 4567)', status: 'Üzemel', trashBags: 15, hasProblem: false, problemText: '' },
  { id: 'pt-g-2', zoneId: 'zone-jurisics', code: 'GASZT-02', name: 'Várkapu Burger & Pulled Pork Truck', type: 'food', x: 55, y: 82, power: '3x32A Ipari', contact: 'Horváth Tamás (+36 30 666 7788)', status: 'BIZTOSÍTÉK LEVÁGVA!', trashBags: 15, hasProblem: true, problemText: 'A fritőz lecsapta a 32A biztosítékot, villanyszerelő úton van!' },
  { id: 'pt-g-3', zoneId: 'zone-jurisics', code: 'GASZT-03', name: 'Kürtőskalács & Rétes Házikó', type: 'food', x: 68, y: 82, power: '3x16A', contact: 'Szabó Éva (+36 20 777 8899)', status: 'Üzemel', trashBags: 8, hasProblem: false, problemText: '' },
  { id: 'pt-g-4', zoneId: 'zone-jurisics', code: 'GASZT-04', name: 'Kézműves Sörök Udvara', type: 'food', x: 80, y: 82, power: '1x16A', contact: 'Molnár Dániel (+36 30 888 9900)', status: 'Üzemel', trashBags: 12, hasProblem: false, problemText: '' },

  // VÁRJÁTSZÓTÉR & VÁRÁROK
  { id: 'pt-ksz-2', zoneId: 'zone-var', code: 'KISSZÍNPAD-2', name: 'Kisszínpad 2 (Várjátszótér Gyerekbirodalom)', type: 'stage', x: 15, y: 15, power: '1x16A', contact: 'Gábor Elnök', status: 'Gyerekprogramok', hasProblem: false, problemText: '' },
  
  // KAPUALJAK
  { id: 'pt-utc-1', zoneId: 'zone-kapualj', code: 'UTC-01', name: 'Hősök Tornya alatti kapualj (Balkan Brass)', type: 'street', x: 38, y: 55, power: '230V Hosszabbító', contact: 'Műszaki Stáb', status: 'Utcazenész játszik', hasProblem: false, problemText: '' },
  { id: 'pt-utc-2', zoneId: 'zone-kapualj', code: 'UTC-02', name: 'Chernel utca sétány kapu', type: 'street', x: 45, y: 12, power: 'Akusztikus', contact: 'Szilveszter', status: 'Szabad sáv', hasProblem: false, problemText: '' }
];

export const INITIAL_INCIDENTS = [
  {
    id: 'inc-1',
    severity: 'critical', // 'critical' (SOS), 'warning', 'resolved', 'info'
    location: 'Jurisics tér — GASZT-02 (Burger Truck)',
    reporter: 'Szilveszter',
    time: '13:42',
    text: 'A fritőz lecsapta a 32A biztosítékot! Bognár Zoltán villanyszerelő értesítve, úton van a helyszínre.',
    isResolved: false,
    resolvedBy: null,
    resolvedAt: null
  },
  {
    id: 'inc-2',
    severity: 'warning',
    location: 'Fő tér — BOR-04 (Láng Pincészet)',
    reporter: 'Önkéntes Csapat',
    time: '13:15',
    text: 'Elfogyott a 120L kommunális kék szemeteszsák. A KTSZE raktárból 2 tekercset ki kell szállítani.',
    isResolved: false,
    resolvedBy: null,
    resolvedAt: null
  },
  {
    id: 'inc-3',
    severity: 'resolved',
    location: 'Hősök Kapuja — Belvárosi Behajtó',
    reporter: 'Gábor',
    time: '12:20',
    text: 'Besh o droM turnébusz parkolási engedély hiánya megoldva, VIP behajtó átadva.',
    isResolved: true,
    resolvedBy: 'Gábor',
    resolvedAt: '12:35'
  }
];

export const INITIAL_SHOPPING_LIST = [
  // 1. NAGY INFRASTRUKTÚRA & SZÍNPADTECHNIKA
  {
    id: 'shp-stage-1',
    name: 'Nagyszínpad 10x8m alumínium fedés + 18kW Line Array hang- és intelligens fényrendszer',
    category: 'Színpad- és Hangtechnika',
    store: 'Stage Pro Hungary Kft.',
    qty: 1,
    unit: 'komplett szett',
    estimatedPrice: 3900000,
    actualPrice: 3900000,
    createdBy: 'Szilveszter',
    createdAt: '2026-04-10 09:15',
    responsible: 'Szilveszter',
    priority: 'Sürgős',
    isPurchased: true,
    purchasedBy: 'Szilveszter',
    purchasedAt: '2026-04-20 14:30',
    hasReceipt: true,
    notes: 'Péntek déli soundcheckre állnia kell a Fő téren!'
  },
  {
    id: 'shp-stage-2',
    name: 'Kisszínpad 1 (Jurisics tér) & Kisszínpad 2 (Várjátszótér) fedett dobogók és alap PA',
    category: 'Színpad- és Hangtechnika',
    store: 'Acoustic Sound Kft.',
    qty: 2,
    unit: 'színpadállomás',
    estimatedPrice: 1450000,
    actualPrice: 1450000,
    createdBy: 'Szilveszter',
    createdAt: '2026-04-12 11:30',
    responsible: 'Szilveszter',
    priority: 'Magas',
    isPurchased: true,
    purchasedBy: 'Szilveszter',
    purchasedAt: '2026-04-25 10:00',
    hasReceipt: true,
    notes: 'Akusztikus és világzenei koncertekhez bemikrofonozva.'
  },
  {
    id: 'shp-power-1',
    name: '60 kVA Csendesített Hangszigetelt Dízel Aggregátor (Nagyszínpad tartalék betáp)',
    category: 'Áram & Gépbérlés',
    store: 'Aggregátor Bérlés Kft.',
    qty: 1,
    unit: 'gép + 200L dízel',
    estimatedPrice: 680000,
    actualPrice: 0,
    createdBy: 'Szilveszter',
    createdAt: '2026-04-15 14:00',
    responsible: 'Műszaki Stáb',
    priority: 'Sürgős',
    isPurchased: false,
    purchasedBy: null,
    purchasedAt: null,
    hasReceipt: true,
    notes: 'Hálózatkimaradás esetére azonnali átkapcsolással.'
  },
  {
    id: 'shp-wc-1',
    name: '10 db Mobil WC sziget (ToiToi) + 4 db kézmosó állomás fertőtlenítővel',
    category: 'Higiénia & Szemétkezelés',
    store: 'ToiToi & Dixi Kft.',
    qty: 14,
    unit: 'kabin/állomás',
    estimatedPrice: 420000,
    actualPrice: 420000,
    createdBy: 'Gábor',
    createdAt: '2026-04-16 10:20',
    responsible: 'Gábor',
    priority: 'Magas',
    isPurchased: true,
    purchasedBy: 'Gábor',
    purchasedAt: '2026-05-02 16:00',
    hasReceipt: true,
    notes: 'Napi 2x szippantás és tisztítás szerződésbe foglalva.'
  },
  {
    id: 'shp-waste-1',
    name: '2 db 10m3 zárt tömörítő hulladékkonténer kihelyezése és napi elszállítása',
    category: 'Higiénia & Szemétkezelés',
    store: 'Kőszegi Kommunális Kft.',
    qty: 2,
    unit: 'konténer',
    estimatedPrice: 380000,
    actualPrice: 380000,
    createdBy: 'Gábor',
    createdAt: '2026-04-16 11:00',
    responsible: 'Gábor',
    priority: 'Normál',
    isPurchased: true,
    purchasedBy: 'Gábor',
    purchasedAt: '2026-05-03 09:15',
    hasReceipt: true,
    notes: 'Jurisics tér sarkára telepítve péntek reggel 07:00-ig.'
  },
  {
    id: 'shp-kordon-1',
    name: '200m Fém Nehézkordon (Nagyszínpad kordonvonal és FOH hangpult védelem)',
    category: 'Biztonság & Kordon',
    store: 'Kordonbér Kft.',
    qty: 80,
    unit: 'elem (2.5m/db)',
    estimatedPrice: 350000,
    actualPrice: 0,
    createdBy: 'Szilveszter',
    createdAt: '2026-04-18 16:45',
    responsible: 'Szilveszter',
    priority: 'Magas',
    isPurchased: false,
    purchasedBy: null,
    purchasedAt: null,
    hasReceipt: true,
    notes: 'Csütörtök délutáni kiszállítással a Fő térre.'
  },
  {
    id: 'shp-print-1',
    name: '500 db A3 és B2 Színes Fesztivál Plakát + 3000 db zsebméretű Műsorfüzet',
    category: 'Nyomda & Reklám',
    store: 'Savaria Nyomda Kft.',
    qty: 3500,
    unit: 'nyomtatvány',
    estimatedPrice: 320000,
    actualPrice: 310000,
    createdBy: 'Zoltán',
    createdAt: '2026-04-20 08:30',
    responsible: 'Zoltán',
    priority: 'Normál',
    isPurchased: true,
    purchasedBy: 'Zoltán',
    purchasedAt: '2026-05-10 13:00',
    hasReceipt: true,
    notes: 'Kőszeg, Szombathely és határmenti települések terjesztésére.'
  },

  // 2. FOGYÓANYAGOK, HULLADÉKKEZELÉS & KELLÉKEK (A SZEMETESZSÁKIG)
  {
    id: 'shp-1',
    name: '120L Extra Erős Szemeteszsákok (Kék Kommunális, 60 mikron)',
    category: 'Higiénia & Szemétkezelés',
    store: 'Metro Szombathely (Nagyker)',
    qty: 30,
    unit: 'tekercs (25db/tek)',
    estimatedPrice: 96000,
    actualPrice: 94500,
    createdBy: 'Szilveszter',
    createdAt: '2026-05-01 10:00',
    responsible: 'Szilveszter',
    priority: 'Sürgős',
    isPurchased: true,
    purchasedBy: 'Szilveszter',
    purchasedAt: '2026-05-18 11:20',
    hasReceipt: true,
    notes: 'KTSZE számlára kérve. Minimum 60 mikronos szakadásmentes minőség!'
  },
  {
    id: 'shp-2',
    name: '120L Sárga Szelektív Műanyag Szemeteszsákok',
    category: 'Higiénia & Szemétkezelés',
    store: 'Metro Szombathely (Nagyker)',
    qty: 20,
    unit: 'tekercs (25db/tek)',
    estimatedPrice: 64000,
    actualPrice: 62000,
    createdBy: 'Zoltán',
    createdAt: '2026-05-01 10:15',
    responsible: 'Önkéntes Csapat',
    priority: 'Normál',
    isPurchased: true,
    purchasedBy: 'Önkéntes Csapat',
    purchasedAt: '2026-05-18 11:45',
    hasReceipt: true,
    notes: 'Ételek utcája és borászatok műanyaghulladékához.'
  },
  {
    id: 'shp-3',
    name: 'Gaffatape Ipari Szövet Ragasztószalag (Fekete & Ezüst)',
    category: 'Kellékek & Barkács',
    store: 'Bauhaus / Praktiker (Barkács)',
    qty: 12,
    unit: 'tekercs (50m)',
    estimatedPrice: 48000,
    actualPrice: 0,
    createdBy: 'Szilveszter',
    createdAt: '2026-05-02 14:00',
    responsible: 'Műszaki Stáb',
    priority: 'Sürgős',
    isPurchased: false,
    purchasedBy: null,
    purchasedAt: null,
    hasReceipt: true,
    notes: 'Színpadi kábelrögzítéshez, taposókhoz, ne hagyjon ragacsot a kövön!'
  },
  {
    id: 'shp-4',
    name: 'Kábelkötegelők (300mm és 500mm vastag ipari gyorskötöző)',
    category: 'Kellékek & Barkács',
    store: 'Bauhaus / Praktiker (Barkács)',
    qty: 5,
    unit: 'csomag (100db/csom)',
    estimatedPrice: 20000,
    actualPrice: 0,
    createdBy: 'Szilveszter',
    createdAt: '2026-05-02 14:15',
    responsible: 'Műszaki Stáb',
    priority: 'Normál',
    isPurchased: false,
    purchasedBy: null,
    purchasedAt: null,
    hasReceipt: true,
    notes: 'Molinók, szponzortáblák és kordonhálók rögzítéséhez.'
  },
  {
    id: 'shp-5',
    name: 'Szénsavmentes Ásványvíz (0.5L palackos kartonok fellépőknek & stábnak)',
    category: 'Catering & Backstage',
    store: 'Metro Szombathely (Nagyker)',
    qty: 40,
    unit: 'karton (24db/karton)',
    estimatedPrice: 115000,
    actualPrice: 0,
    createdBy: 'Szilveszter',
    createdAt: '2026-05-05 09:30',
    responsible: 'Önkéntes Csapat',
    priority: 'Magas',
    isPurchased: false,
    purchasedBy: null,
    purchasedAt: null,
    hasReceipt: true,
    notes: 'Nagyszínpad és fellépők öltözősátrába, behűtve kell tartani!'
  },
  {
    id: 'shp-6',
    name: 'Szemes Kávé (Lavazza) & Teafilterek, Méz, Citromlé',
    category: 'Catering & Backstage',
    store: 'Metro Szombathely (Nagyker)',
    qty: 6,
    unit: 'kg kávé + tea csomagok',
    estimatedPrice: 42000,
    actualPrice: 0,
    createdBy: 'Szilveszter',
    createdAt: '2026-05-05 09:45',
    responsible: 'Szilveszter',
    priority: 'Normál',
    isPurchased: false,
    purchasedBy: null,
    purchasedAt: null,
    hasReceipt: true,
    notes: 'Backstage kávégéphez a Jurisics vár öltözőibe.'
  },
  {
    id: 'shp-7',
    name: 'Vízálló Vastag Alkoholos Filctollak & Laminálófólia A4/A5',
    category: 'Iroda & Nyomda',
    store: 'Irodaszer & Nyomda',
    qty: 1,
    unit: 'készlet (12 filc + 100 fólia)',
    estimatedPrice: 14000,
    actualPrice: 13500,
    createdBy: 'Szilveszter',
    createdAt: '2026-05-06 11:20',
    responsible: 'Szilveszter',
    priority: 'Normál',
    isPurchased: true,
    purchasedBy: 'Szilveszter',
    purchasedAt: '2026-05-19 14:10',
    hasReceipt: true,
    notes: 'Beléptető passzokhoz és műszaki eligazító táblákhoz.'
  },
  {
    id: 'shp-8',
    name: 'Tiszta Pamut Fekete Törölközők (Fellépői riderhez)',
    category: 'Catering & Backstage',
    store: 'Kőszegi Élelmiszer / Coop / Spar',
    qty: 20,
    unit: 'db',
    estimatedPrice: 35000,
    actualPrice: 0,
    createdBy: 'Szilveszter',
    createdAt: '2026-05-08 15:30',
    responsible: 'Önkéntes Csapat',
    priority: 'Normál',
    isPurchased: false,
    purchasedBy: null,
    purchasedAt: null,
    hasReceipt: true,
    notes: 'Ocho Macho és G.w.M fellépői szerződésben kikötött fekete pamut törölköző.'
  },
  {
    id: 'shp-9',
    name: 'Kézfertőtlenítő Gél Utántöltő Kanna (5 literes)',
    category: 'Higiénia & Szemétkezelés',
    store: 'Metro Szombathely (Nagyker)',
    qty: 3,
    unit: 'kanna (5L)',
    estimatedPrice: 24000,
    actualPrice: 0,
    createdBy: 'Zoltán',
    createdAt: '2026-05-10 10:00',
    responsible: 'Önkéntes Csapat',
    priority: 'Normál',
    isPurchased: false,
    purchasedBy: null,
    purchasedAt: null,
    hasReceipt: true,
    notes: 'Kézmosó állomásokhoz a Fő téren és Jurisics téren.'
  }
];




